#ifndef SHS_COMMON_LIGHT_CONSTANTS_GLSL
#define SHS_COMMON_LIGHT_CONSTANTS_GLSL

const uint SHS_LIGHT_TYPE_DIRECTIONAL = 0u;
const uint SHS_LIGHT_TYPE_POINT = 1u;
const uint SHS_LIGHT_TYPE_SPOT = 2u;
const uint SHS_LIGHT_TYPE_RECT_AREA = 3u;
const uint SHS_LIGHT_TYPE_TUBE_AREA = 4u;

const uint SHS_LIGHT_FLAG_ENABLED = 1u;
const uint SHS_LIGHT_FLAG_AFFECTS_DIFFUSE = 2u;
const uint SHS_LIGHT_FLAG_AFFECTS_SPECULAR = 4u;
const uint SHS_LIGHT_FLAG_AFFECTS_SHADOWS = 8u;

const uint SHS_LIGHT_ATTEN_LINEAR = 0u;
const uint SHS_LIGHT_ATTEN_SMOOTH = 1u;
const uint SHS_LIGHT_ATTEN_INVERSE_SQUARE = 2u;

#endif // SHS_COMMON_LIGHT_CONSTANTS_GLSL
